---
  - name: Check if SHOPPER App exists
    stat: path="{{ snova_path }}/apps/shopper"
    register: app

  - name: Get the SHOPPER app
    command: snova get-app shopper {{ shopper_repo_url }} --branch {{ shopper_branch }}
    args:
      creates: "{{ snova_path }}/apps/shopper"
      chdir: "{{ snova_path }}"
    when: not app.stat.exists and not without_shopper

  - name: Check whether the site already exists
    stat: path="{{ snova_path }}/sites/{{ site }}"
    register: site_folder
    when: not without_site

  - name: Create a new site
    command: "snova new-site {{ site }} --admin-password '{{ admin_password }}' --mariadb-root-password '{{ mysql_root_password }}'"
    args:
      chdir: "{{ snova_path }}"
    when: not without_site and not site_folder.stat.exists

  - name: Install SHOPPER to default site
    command: "snova --site {{ site }} install-app shopper"
    args:
      chdir: "{{ snova_path }}"
    when: not without_site and not without_shopper
...