---
- name: Install deps
  yum:
    name:
      - policycoreutils-python
      - selinux-policy-devel
    state: present
  when: ansible_distribution == 'CentOS'

- name: Check enabled SELinux modules
  shell: semanage module -l
  register: enabled_modules
  when: ansible_distribution == 'CentOS'

- name: Copy sparrow_selinux policy
  copy: src=sparrow_selinux.te dest=/root/sparrow_selinux.te
  register: dest_sparrow_selinux_te
  when: ansible_distribution == 'CentOS'

- name: Compile sparrow_selinux policy
  shell: "make -f /usr/share/selinux/devel/Makefile sparrow_selinux.pp && semodule -i sparrow_selinux.pp"
  args:
    chdir: /root/
  when: "ansible_distribution == 'CentOS' and enabled_modules.stdout.find('sparrow_selinux') == -1 or dest_sparrow_selinux_te.changed"
...