---
- name: Setup production
  become: yes
  become_user: root
  command: bench setup production {{sparrow_user }} --yes
  args:
    chdir: '{{ bench_path }}'

- name: Setup Sudoers
  become: yes
  become_user: root
  command: bench setup sudoers {{sparrow_user }}
  args:
    chdir: '{{ bench_path }}'

- name: Set correct permissions on bench.log
  file:
    path: '{{ bench_path }}/logs/bench.log'
    owner: '{{sparrow_user }}'
    group: '{{sparrow_user }}'
  become: yes
  become_user: root

- name: Restart the bench
  command: bench restart
  args:
    chdir: '{{ bench_path }}'
...